language: node_js
node_js:
  - "node"

branches:
  only:
  - master


after_success:
  - echo ${TRAVIS_PULL_REQUEST}
  - echo ${TRAVIS_BRANCH}
  - echo ${TRAVIS_TAG}
  - echo ${TRAVIS_EVENT_TYPE}
  - node index.js
  - git clone https://github.com/una-club/una-newsletter.git repo
  - cd repo
  - git checkout gh-pages
  - mkdir history/
  - mv ../history/* history/
  - git config user.email mickael.a.tardy@gmail.com
  - git config user.name mickaeltardy
  - git add history/*
  - git commit -m "Publish newsletter from travis"
  - git push --repo=https://${GITHUB_TOKEN}@github.com/una-club/una-newsletter.git
  - cd ..
  - git clone https://github.com/una-club/una-club.github.io.git website
  - cd website
  - git config user.email mickael.a.tardy@gmail.com
  - git config user.name mickaeltardy
  - git submodule update --init --recursive
  - cd una-newsletter
  - git checkout gh-pages
  - cd ..
  - git add una-newsletter
  - git commit -m "Update newsletter"
  - git push --repo=https://${GITHUB_TOKEN}@github.com/una-club/una-club.github.io.git
