language: node_js
node_js:
  - "node"

branches:
  only:
  - master

deploy:
  skip_cleanup: true

before_install:
  - git clone https://github.com/una-club/una-newsletter.git repo
  - mkdir repo/history/
  - mv history/* repo/history/
  - cd repo
  - git config user.email mickael.a.tardy@gmail.com
  - git config user.name mickaeltardy
  - git add history/*
  - git commit -m "Publish newsletter from travis"
  - git push --repo=https://${GITHUB_TOKEN}@github.com/una-club/una-newsletter.git
  - cd ..
  - git clone https://github.com/una-club/una-club.github.io.git website
  - cd website
  - git config user.email mickael.a.tardy@gmail.com
  - git config user.name mickaeltardy
  - git submodule update --init --recursive
  - cd una-newsletter
  - git checkout develop
  - cd ..
  - git add una-newsletter
  - git commit -m "Update newsletter"
  - git push --repo=https://${GITHUB_TOKEN}@github.com/una-club/una-club.github.io.git
